-- Historical migration retained for Flyway compatibility. The table is
-- removed by V13 because AI configuration is now owned by safefleet_ai.
CREATE TABLE IF NOT EXISTS agent_ai_configurations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    encrypted_api_key TEXT NULL,
    model_name VARCHAR(80) NOT NULL DEFAULT 'gpt-4o-mini',
    base_url VARCHAR(255) NOT NULL DEFAULT 'https://api.openai.com/v1',
    max_steps INT NOT NULL DEFAULT 6,
    updated_by BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT fk_agent_ai_config_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id),
    CONSTRAINT chk_agent_ai_config_max_steps CHECK (max_steps BETWEEN 2 AND 10)
);

INSERT INTO agent_ai_configurations (
    enabled,
    encrypted_api_key,
    model_name,
    base_url,
    max_steps,
    created_at,
    deleted
)
SELECT FALSE, NULL, 'gpt-4o-mini', 'https://api.openai.com/v1', 6, CURRENT_TIMESTAMP(6), FALSE
WHERE NOT EXISTS (SELECT 1 FROM agent_ai_configurations);
