CREATE TABLE pre_trip_checklists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    vehicle_id BIGINT NULL,
    exterior_checked BOOLEAN NOT NULL DEFAULT FALSE,
    tires_checked BOOLEAN NOT NULL DEFAULT FALSE,
    brake_checked BOOLEAN NOT NULL DEFAULT FALSE,
    lights_checked BOOLEAN NOT NULL DEFAULT FALSE,
    camera_checked BOOLEAN NOT NULL DEFAULT FALSE,
    gps_checked BOOLEAN NOT NULL DEFAULT FALSE,
    documents_checked BOOLEAN NOT NULL DEFAULT FALSE,
    checklist_json TEXT NULL,
    note VARCHAR(500) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_pre_trip_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT fk_pre_trip_driver FOREIGN KEY (driver_id) REFERENCES drivers(id),
    CONSTRAINT fk_pre_trip_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);
CREATE INDEX idx_pre_trip_trip_driver ON pre_trip_checklists (trip_id, driver_id);
CREATE INDEX idx_pre_trip_driver_created ON pre_trip_checklists (driver_id, created_at);

CREATE TABLE agent_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    driver_id BIGINT NULL,
    trip_id BIGINT NULL,
    command_type VARCHAR(30) NOT NULL,
    transcript VARCHAR(1000) NOT NULL,
    normalized_command VARCHAR(255) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED',
    response_text VARCHAR(1000) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_agent_command_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_agent_command_driver FOREIGN KEY (driver_id) REFERENCES drivers(id),
    CONSTRAINT fk_agent_command_trip FOREIGN KEY (trip_id) REFERENCES trips(id)
);
CREATE INDEX idx_agent_user_created ON agent_commands (user_id, created_at);
CREATE INDEX idx_agent_driver_created ON agent_commands (driver_id, created_at);
