-- SafeFleet mobile/offline, navigation, evidence and per-user notification state.
-- All changes are additive so production upgrades remain compatible with V1-V3.

CREATE TABLE mobile_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    platform VARCHAR(20) NOT NULL,
    app_version VARCHAR(40),
    os_version VARCHAR(80),
    device_model VARCHAR(120),
    last_seen_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_mobile_devices_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_mobile_devices_uuid UNIQUE (device_uuid)
);
CREATE INDEX idx_mobile_devices_user ON mobile_devices (user_id);
CREATE INDEX idx_mobile_devices_last_seen ON mobile_devices (last_seen_at);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_used_at TIMESTAMP(6),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash)
);
CREATE INDEX idx_refresh_tokens_user_active ON refresh_tokens (user_id, revoked_at, expires_at);
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at);

CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    request_method VARCHAR(10) NOT NULL,
    request_path VARCHAR(255) NOT NULL,
    request_hash VARCHAR(64),
    response_status INT NOT NULL,
    response_body TEXT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_idempotency_records_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_idempotency_user_key UNIQUE (user_id, idempotency_key)
);
CREATE INDEX idx_idempotency_expires ON idempotency_records (expires_at);

CREATE TABLE sync_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_uuid VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    device_id BIGINT,
    item_count INT NOT NULL DEFAULT 0,
    accepted_count INT NOT NULL DEFAULT 0,
    duplicate_count INT NOT NULL DEFAULT 0,
    rejected_count INT NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    error_summary VARCHAR(1000),
    received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    CONSTRAINT fk_sync_batches_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_sync_batches_device FOREIGN KEY (device_id) REFERENCES mobile_devices(id),
    CONSTRAINT uk_sync_batches_uuid UNIQUE (batch_uuid)
);
CREATE INDEX idx_sync_batches_user_received ON sync_batches (user_id, received_at);

ALTER TABLE telemetry_logs
    ADD COLUMN client_event_id VARCHAR(100),
    ADD COLUMN sync_batch_id BIGINT,
    ADD COLUMN recorded_at TIMESTAMP(6),
    ADD COLUMN received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD CONSTRAINT fk_telemetry_sync_batch FOREIGN KEY (sync_batch_id) REFERENCES sync_batches(id),
    ADD CONSTRAINT uk_telemetry_driver_client_event UNIQUE (driver_id, client_event_id);
CREATE INDEX idx_telemetry_received_at ON telemetry_logs (received_at);

ALTER TABLE safety_events
    ADD COLUMN client_event_id VARCHAR(100),
    ADD COLUMN sync_batch_id BIGINT,
    ADD COLUMN received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD CONSTRAINT fk_safety_sync_batch FOREIGN KEY (sync_batch_id) REFERENCES sync_batches(id),
    ADD CONSTRAINT uk_safety_driver_client_event UNIQUE (driver_id, client_event_id);
CREATE INDEX idx_safety_received_at ON safety_events (received_at);

ALTER TABLE incidents
    ADD COLUMN client_event_id VARCHAR(100),
    ADD COLUMN sync_batch_id BIGINT,
    ADD COLUMN received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD CONSTRAINT fk_incidents_sync_batch FOREIGN KEY (sync_batch_id) REFERENCES sync_batches(id),
    ADD CONSTRAINT uk_incident_driver_client_event UNIQUE (driver_id, client_event_id);
CREATE INDEX idx_incidents_received_at ON incidents (received_at);

ALTER TABLE flood_reports
    ADD COLUMN client_event_id VARCHAR(100),
    ADD COLUMN sync_batch_id BIGINT,
    ADD COLUMN received_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD CONSTRAINT fk_flood_sync_batch FOREIGN KEY (sync_batch_id) REFERENCES sync_batches(id),
    ADD CONSTRAINT uk_flood_driver_client_event UNIQUE (reported_by_driver_id, client_event_id);
CREATE INDEX idx_flood_received_at ON flood_reports (received_at);

CREATE TABLE navigation_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid VARCHAR(100) NOT NULL,
    driver_id BIGINT NOT NULL,
    vehicle_id BIGINT,
    trip_id BIGINT,
    origin_lat DOUBLE PRECISION NOT NULL,
    origin_lng DOUBLE PRECISION NOT NULL,
    destination_lat DOUBLE PRECISION NOT NULL,
    destination_lng DOUBLE PRECISION NOT NULL,
    destination_name VARCHAR(255),
    selected_candidate_id BIGINT,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMP(6),
    ended_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_navigation_sessions_driver FOREIGN KEY (driver_id) REFERENCES drivers(id),
    CONSTRAINT fk_navigation_sessions_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_navigation_sessions_trip FOREIGN KEY (trip_id) REFERENCES trips(id),
    CONSTRAINT uk_navigation_sessions_uuid UNIQUE (session_uuid)
);
CREATE INDEX idx_navigation_sessions_driver_status ON navigation_sessions (driver_id, status);
CREATE INDEX idx_navigation_sessions_trip ON navigation_sessions (trip_id);

CREATE TABLE navigation_route_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navigation_session_id BIGINT NOT NULL,
    route_index INT NOT NULL,
    label VARCHAR(120) NOT NULL,
    distance_meters INT NOT NULL,
    duration_seconds INT NOT NULL,
    risk_score DECIMAL(7, 3) NOT NULL DEFAULT 0,
    flood_intersection_count INT NOT NULL DEFAULT 0,
    is_recommended BOOLEAN NOT NULL DEFAULT FALSE,
    geometry_json TEXT NOT NULL,
    warnings_json TEXT,
    provider VARCHAR(40) NOT NULL DEFAULT 'LOCAL_DEMO',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_navigation_candidates_session
        FOREIGN KEY (navigation_session_id) REFERENCES navigation_sessions(id),
    CONSTRAINT uk_navigation_candidate_index UNIQUE (navigation_session_id, route_index)
);
CREATE INDEX idx_navigation_candidate_recommended ON navigation_route_candidates (navigation_session_id, is_recommended);

ALTER TABLE navigation_sessions
    ADD CONSTRAINT fk_navigation_sessions_selected_candidate
        FOREIGN KEY (selected_candidate_id) REFERENCES navigation_route_candidates(id);

CREATE TABLE navigation_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navigation_session_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    distance_to_hazard_meters INT,
    payload_json TEXT,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_navigation_events_session
        FOREIGN KEY (navigation_session_id) REFERENCES navigation_sessions(id)
);
CREATE INDEX idx_navigation_events_session_created ON navigation_events (navigation_session_id, created_at);
CREATE INDEX idx_navigation_events_type_created ON navigation_events (event_type, created_at);

CREATE TABLE safety_event_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    safety_event_id BIGINT,
    incident_id BIGINT,
    uploaded_by BIGINT NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255),
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    captured_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_evidence_safety_event FOREIGN KEY (safety_event_id) REFERENCES safety_events(id),
    CONSTRAINT fk_evidence_incident FOREIGN KEY (incident_id) REFERENCES incidents(id),
    CONSTRAINT fk_evidence_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id),
    CONSTRAINT uk_evidence_object_key UNIQUE (object_key)
);
CREATE INDEX idx_evidence_safety_event ON safety_event_evidence (safety_event_id);
CREATE INDEX idx_evidence_incident ON safety_event_evidence (incident_id);
CREATE INDEX idx_evidence_sha256 ON safety_event_evidence (sha256);

CREATE TABLE push_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    device_id BIGINT,
    provider VARCHAR(30) NOT NULL,
    token VARCHAR(512) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_used_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_push_tokens_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_push_tokens_device FOREIGN KEY (device_id) REFERENCES mobile_devices(id),
    CONSTRAINT uk_push_tokens_provider_token UNIQUE (provider, token)
);
CREATE INDEX idx_push_tokens_user_enabled ON push_tokens (user_id, enabled);

CREATE TABLE pending_push_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT,
    user_id BIGINT NOT NULL,
    push_token_id BIGINT,
    title VARCHAR(150) NOT NULL,
    body VARCHAR(500) NOT NULL,
    data_json TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    sent_at TIMESTAMP(6),
    last_error VARCHAR(1000),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_pending_push_notification FOREIGN KEY (notification_id) REFERENCES notifications(id),
    CONSTRAINT fk_pending_push_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_pending_push_token FOREIGN KEY (push_token_id) REFERENCES push_tokens(id)
);
CREATE INDEX idx_pending_push_dispatch ON pending_push_notifications (status, next_attempt_at);
CREATE INDEX idx_pending_push_user_created ON pending_push_notifications (user_id, created_at);

CREATE TABLE notification_reads (
    notification_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    read_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (notification_id, user_id),
    CONSTRAINT fk_notification_reads_notification FOREIGN KEY (notification_id) REFERENCES notifications(id),
    CONSTRAINT fk_notification_reads_user FOREIGN KEY (user_id) REFERENCES users(id)
);
CREATE INDEX idx_notification_reads_user ON notification_reads (user_id, read_at);
