ALTER TABLE navigation_route_candidates
    ADD COLUMN total_score DECIMAL(10, 3) NOT NULL DEFAULT 0,
    ADD COLUMN flood_penalty DECIMAL(10, 3) NOT NULL DEFAULT 0,
    ADD COLUMN vehicle_restriction_penalty DECIMAL(10, 3) NOT NULL DEFAULT 0,
    ADD COLUMN driver_time_penalty DECIMAL(10, 3) NOT NULL DEFAULT 0,
    ADD COLUMN safe BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN blocked BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN steps_json TEXT;

ALTER TABLE navigation_events
    ADD COLUMN distance_to_route_meters INT,
    ADD COLUMN gps_accuracy_meters DECIMAL(8, 2),
    ADD COLUMN occurred_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
CREATE INDEX idx_navigation_events_session_occurred ON navigation_events (navigation_session_id, occurred_at);

CREATE TABLE sync_batch_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_batch_id BIGINT NOT NULL,
    item_index INT NOT NULL,
    client_event_id VARCHAR(100),
    item_type VARCHAR(40) NOT NULL,
    item_status VARCHAR(30) NOT NULL,
    entity_id BIGINT,
    error_message VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_sync_batch_items_batch FOREIGN KEY (sync_batch_id) REFERENCES sync_batches(id),
    CONSTRAINT uk_sync_batch_item_event UNIQUE (sync_batch_id, client_event_id),
    CONSTRAINT uk_sync_batch_item_index UNIQUE (sync_batch_id, item_index)
);
CREATE INDEX idx_sync_batch_items_batch ON sync_batch_items (sync_batch_id);
