CREATE TABLE document_ocr_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    original_filename VARCHAR(255),
    content_type VARCHAR(80) NOT NULL,
    image_data BYTEA NULL,
    project_address VARCHAR(500),
    engine VARCHAR(120),
    elapsed_ms BIGINT,
    error_message VARCHAR(500),
    started_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_document_ocr_job_owner FOREIGN KEY (owner_user_id) REFERENCES users(id)
);
CREATE INDEX idx_document_ocr_job_owner_created ON document_ocr_jobs (owner_user_id, created_at);
CREATE INDEX idx_document_ocr_job_status_created ON document_ocr_jobs (status, created_at);
