-- SafeFleet PostgreSQL 16+ target baseline.
-- This is a clean target schema, not an in-place MySQL migration script.

CREATE SCHEMA IF NOT EXISTS safefleet;
SET search_path TO safefleet, public;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

-- ---------------------------------------------------------------------------
-- Identity and access management
-- ---------------------------------------------------------------------------

CREATE TABLE permissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(100) NOT NULL,
    description varchar(255),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_permissions_code_active ON permissions (code) WHERE NOT deleted;

CREATE TABLE roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(255),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_roles_name_active ON roles (lower(name)) WHERE NOT deleted;

CREATE TABLE role_permissions (
    role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id bigint NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(80) NOT NULL,
    email varchar(120) NOT NULL,
    password_hash varchar(255) NOT NULL,
    full_name varchar(150) NOT NULL,
    phone varchar(20),
    status varchar(30) NOT NULL,
    role_id bigint NOT NULL REFERENCES roles(id),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_users_username_active ON users (lower(username)) WHERE NOT deleted;
CREATE UNIQUE INDEX uk_users_email_active ON users (lower(email)) WHERE NOT deleted;
CREATE INDEX idx_users_role_status ON users (role_id, status) WHERE NOT deleted;

CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE,
    expires_at timestamptz(6) NOT NULL,
    revoked_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    last_used_at timestamptz(6),
    CONSTRAINT ck_refresh_token_hash CHECK (token_hash ~ '^[0-9a-fA-F]{64}$')
);
CREATE INDEX idx_refresh_tokens_user_active ON refresh_tokens (user_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- Fleet and assignment history
-- ---------------------------------------------------------------------------

CREATE TABLE drivers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint UNIQUE REFERENCES users(id),
    full_name varchar(150) NOT NULL,
    phone varchar(20) NOT NULL,
    email varchar(120),
    address varchar(255),
    license_number varchar(50) NOT NULL,
    license_class varchar(20) NOT NULL,
    license_expired_at date NOT NULL,
    status varchar(30) NOT NULL,
    safety_score integer NOT NULL DEFAULT 100 CHECK (safety_score BETWEEN 0 AND 100),
    driving_time_today_minutes integer NOT NULL DEFAULT 0 CHECK (driving_time_today_minutes >= 0),
    continuous_driving_minutes integer NOT NULL DEFAULT 0 CHECK (continuous_driving_minutes >= 0),
    total_trips integer NOT NULL DEFAULT 0 CHECK (total_trips >= 0),
    total_alerts integer NOT NULL DEFAULT 0 CHECK (total_alerts >= 0),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_drivers_license_active ON drivers (upper(license_number)) WHERE NOT deleted;
CREATE INDEX idx_drivers_status ON drivers (status) WHERE NOT deleted;

CREATE TABLE vehicles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number varchar(30) NOT NULL,
    vehicle_type varchar(30) NOT NULL,
    brand varchar(80),
    model varchar(80),
    manufacture_year integer CHECK (manufacture_year BETWEEN 1900 AND 2200),
    load_capacity numeric(10,2) CHECK (load_capacity IS NULL OR load_capacity >= 0),
    seat_count integer CHECK (seat_count IS NULL OR seat_count >= 0),
    fuel_type varchar(30),
    status varchar(30) NOT NULL,
    inspection_expired_at date,
    insurance_expired_at date,
    last_lat double precision CHECK (last_lat IS NULL OR last_lat BETWEEN -90 AND 90),
    last_lng double precision CHECK (last_lng IS NULL OR last_lng BETWEEN -180 AND 180),
    last_speed double precision CHECK (last_speed IS NULL OR last_speed >= 0),
    last_updated_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_vehicles_plate_active ON vehicles (upper(regexp_replace(plate_number, '[^A-Za-z0-9]', '', 'g')))
    WHERE NOT deleted;
CREATE INDEX idx_vehicles_type_status ON vehicles (vehicle_type, status) WHERE NOT deleted;

CREATE TABLE devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code varchar(50) NOT NULL,
    name varchar(120) NOT NULL,
    type varchar(40) NOT NULL,
    status varchar(30) NOT NULL,
    phone varchar(20),
    serial_number varchar(80),
    firmware_version varchar(40),
    last_seen_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_devices_code_active ON devices (device_code) WHERE NOT deleted;
CREATE INDEX idx_devices_type_status ON devices (type, status) WHERE NOT deleted;

CREATE TABLE driver_vehicle_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id bigint NOT NULL REFERENCES drivers(id),
    vehicle_id bigint NOT NULL REFERENCES vehicles(id),
    assigned_by_user_id bigint REFERENCES users(id),
    assigned_at timestamptz(6) NOT NULL DEFAULT now(),
    ended_at timestamptz(6),
    reason varchar(255),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT ck_driver_vehicle_assignment_time CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);
CREATE UNIQUE INDEX uk_active_assignment_driver ON driver_vehicle_assignments (driver_id) WHERE ended_at IS NULL;
CREATE UNIQUE INDEX uk_active_assignment_vehicle ON driver_vehicle_assignments (vehicle_id) WHERE ended_at IS NULL;
CREATE INDEX idx_assignment_vehicle_history ON driver_vehicle_assignments (vehicle_id, assigned_at DESC);

CREATE TABLE vehicle_device_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id bigint NOT NULL REFERENCES vehicles(id),
    device_id bigint NOT NULL REFERENCES devices(id),
    device_role varchar(30) NOT NULL,
    assigned_at timestamptz(6) NOT NULL DEFAULT now(),
    ended_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT ck_vehicle_device_assignment_time CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);
CREATE UNIQUE INDEX uk_active_vehicle_device_role ON vehicle_device_assignments (vehicle_id, device_role)
    WHERE ended_at IS NULL;
CREATE UNIQUE INDEX uk_active_device_assignment ON vehicle_device_assignments (device_id)
    WHERE ended_at IS NULL;

CREATE TABLE device_connection_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id bigint NOT NULL REFERENCES devices(id),
    status varchar(30) NOT NULL,
    lat double precision CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    lng double precision CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    note varchar(255),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_device_logs_device_created ON device_connection_logs (device_id, created_at DESC);

-- Catalog for bytes stored in MinIO/S3. Do not store the file body here.
CREATE TABLE object_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id bigint REFERENCES users(id),
    storage_provider varchar(20) NOT NULL DEFAULT 'MINIO',
    bucket_name varchar(100) NOT NULL,
    object_key varchar(500) NOT NULL,
    original_filename varchar(255),
    content_type varchar(120) NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    sha256 char(64) NOT NULL,
    encryption_key_ref varchar(255),
    retention_until timestamptz(6),
    status varchar(30) NOT NULL DEFAULT 'AVAILABLE',
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    deleted_at timestamptz(6),
    CONSTRAINT ck_object_asset_sha256 CHECK (sha256 ~ '^[0-9a-fA-F]{64}$'),
    UNIQUE (bucket_name, object_key)
);
CREATE INDEX idx_object_assets_sha256 ON object_assets (sha256);
CREATE INDEX idx_object_assets_owner_created ON object_assets (owner_user_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Trips and operational workflow
-- ---------------------------------------------------------------------------

CREATE TABLE trips (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_code varchar(50) NOT NULL UNIQUE,
    vehicle_id bigint REFERENCES vehicles(id),
    driver_id bigint REFERENCES drivers(id),
    start_location varchar(255) NOT NULL,
    start_lat double precision CHECK (start_lat IS NULL OR start_lat BETWEEN -90 AND 90),
    start_lng double precision CHECK (start_lng IS NULL OR start_lng BETWEEN -180 AND 180),
    end_location varchar(255) NOT NULL,
    end_lat double precision CHECK (end_lat IS NULL OR end_lat BETWEEN -90 AND 90),
    end_lng double precision CHECK (end_lng IS NULL OR end_lng BETWEEN -180 AND 180),
    waypoints_json jsonb,
    planned_route_json jsonb,
    actual_route_json jsonb,
    planned_start_time timestamptz(6),
    actual_start_time timestamptz(6),
    estimated_end_time timestamptz(6),
    actual_end_time timestamptz(6),
    status varchar(30) NOT NULL,
    progress integer NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    risk_level varchar(30) NOT NULL,
    cancel_reason varchar(255),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_trips_driver_status_time ON trips (driver_id, status, planned_start_time) WHERE NOT deleted;
CREATE INDEX idx_trips_vehicle_status_time ON trips (vehicle_id, status, planned_start_time) WHERE NOT deleted;
CREATE INDEX idx_trips_planned_route_gin ON trips USING gin (planned_route_json jsonb_path_ops)
    WHERE planned_route_json IS NOT NULL;

CREATE TABLE trip_timelines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id bigint NOT NULL REFERENCES trips(id),
    action varchar(80) NOT NULL,
    actor_id bigint REFERENCES users(id),
    note varchar(500),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_trip_timelines_trip_created ON trip_timelines (trip_id, created_at);

CREATE TABLE driving_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id bigint NOT NULL REFERENCES drivers(id),
    vehicle_id bigint REFERENCES vehicles(id),
    trip_id bigint REFERENCES trips(id),
    status varchar(30) NOT NULL,
    started_at timestamptz(6) NOT NULL,
    paused_at timestamptz(6),
    resumed_at timestamptz(6),
    ended_at timestamptz(6),
    continuous_minutes integer NOT NULL DEFAULT 0 CHECK (continuous_minutes >= 0),
    total_minutes integer NOT NULL DEFAULT 0 CHECK (total_minutes >= 0),
    over_driving_alert_created boolean NOT NULL DEFAULT false,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT ck_driving_session_time CHECK (ended_at IS NULL OR ended_at >= started_at)
);
CREATE INDEX idx_driving_sessions_driver_status ON driving_sessions (driver_id, status) WHERE NOT deleted;

CREATE TABLE driver_work_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id bigint NOT NULL REFERENCES drivers(id),
    trip_id bigint REFERENCES trips(id),
    work_date date NOT NULL,
    driving_minutes integer NOT NULL DEFAULT 0 CHECK (driving_minutes >= 0),
    rest_minutes integer NOT NULL DEFAULT 0 CHECK (rest_minutes >= 0),
    note varchar(500),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_driver_work_logs_driver_date ON driver_work_logs (driver_id, work_date DESC) WHERE NOT deleted;

CREATE TABLE pre_trip_checklists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id bigint NOT NULL REFERENCES trips(id),
    driver_id bigint NOT NULL REFERENCES drivers(id),
    vehicle_id bigint REFERENCES vehicles(id),
    exterior_checked boolean NOT NULL DEFAULT false,
    tires_checked boolean NOT NULL DEFAULT false,
    brake_checked boolean NOT NULL DEFAULT false,
    lights_checked boolean NOT NULL DEFAULT false,
    camera_checked boolean NOT NULL DEFAULT false,
    gps_checked boolean NOT NULL DEFAULT false,
    documents_checked boolean NOT NULL DEFAULT false,
    checklist_json jsonb,
    note varchar(500),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_pre_trip_trip_driver ON pre_trip_checklists (trip_id, driver_id) WHERE NOT deleted;

-- ---------------------------------------------------------------------------
-- Offline/mobile synchronization
-- ---------------------------------------------------------------------------

CREATE TABLE mobile_devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_uuid varchar(100) NOT NULL UNIQUE,
    user_id bigint NOT NULL REFERENCES users(id),
    platform varchar(20) NOT NULL,
    app_version varchar(40),
    os_version varchar(80),
    device_model varchar(120),
    last_seen_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_mobile_devices_user ON mobile_devices (user_id) WHERE NOT deleted;

CREATE TABLE idempotency_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    idempotency_key varchar(120) NOT NULL,
    request_method varchar(10) NOT NULL,
    request_path varchar(255) NOT NULL,
    request_hash char(64),
    response_status integer NOT NULL,
    response_body jsonb,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    expires_at timestamptz(6) NOT NULL,
    UNIQUE (user_id, idempotency_key)
);
CREATE INDEX idx_idempotency_expires ON idempotency_records (expires_at);

CREATE TABLE sync_batches (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_uuid varchar(100) NOT NULL UNIQUE,
    user_id bigint NOT NULL REFERENCES users(id),
    device_id bigint REFERENCES mobile_devices(id),
    item_count integer NOT NULL DEFAULT 0 CHECK (item_count >= 0),
    accepted_count integer NOT NULL DEFAULT 0 CHECK (accepted_count >= 0),
    duplicate_count integer NOT NULL DEFAULT 0 CHECK (duplicate_count >= 0),
    rejected_count integer NOT NULL DEFAULT 0 CHECK (rejected_count >= 0),
    status varchar(30) NOT NULL,
    error_summary varchar(1000),
    received_at timestamptz(6) NOT NULL DEFAULT now(),
    completed_at timestamptz(6)
);
CREATE INDEX idx_sync_batches_user_received ON sync_batches (user_id, received_at DESC);

CREATE TABLE sync_batch_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_batch_id bigint NOT NULL REFERENCES sync_batches(id) ON DELETE CASCADE,
    item_index integer NOT NULL,
    client_event_id varchar(100),
    item_type varchar(40) NOT NULL,
    item_status varchar(30) NOT NULL,
    entity_id bigint,
    error_message varchar(500),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    UNIQUE (sync_batch_id, item_index)
);

CREATE TABLE mobile_command_receipts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    client_event_id varchar(100) NOT NULL,
    operation varchar(50) NOT NULL,
    trip_id bigint REFERENCES trips(id),
    response_json jsonb NOT NULL,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false,
    UNIQUE (user_id, client_event_id, operation)
);

-- ---------------------------------------------------------------------------
-- Telemetry, safety and incident management
-- ---------------------------------------------------------------------------

CREATE TABLE telemetry_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id bigint NOT NULL REFERENCES vehicles(id),
    driver_id bigint REFERENCES drivers(id),
    trip_id bigint REFERENCES trips(id),
    lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
    speed double precision CHECK (speed IS NULL OR speed >= 0),
    heading double precision CHECK (heading IS NULL OR heading BETWEEN 0 AND 360),
    battery_level integer CHECK (battery_level IS NULL OR battery_level BETWEEN 0 AND 100),
    gps_status varchar(30) NOT NULL,
    client_event_id varchar(100),
    sync_batch_id bigint REFERENCES sync_batches(id),
    recorded_at timestamptz(6),
    received_at timestamptz(6) NOT NULL DEFAULT now(),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uk_telemetry_driver_client_event ON telemetry_logs (driver_id, client_event_id)
    WHERE client_event_id IS NOT NULL;
CREATE INDEX idx_telemetry_vehicle_recorded ON telemetry_logs (vehicle_id, recorded_at DESC);
CREATE INDEX idx_telemetry_trip_recorded ON telemetry_logs (trip_id, recorded_at DESC) WHERE trip_id IS NOT NULL;
CREATE INDEX idx_telemetry_received_brin ON telemetry_logs USING brin (received_at);

CREATE TABLE safety_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(40) NOT NULL,
    severity varchar(30) NOT NULL,
    vehicle_id bigint REFERENCES vehicles(id),
    driver_id bigint REFERENCES drivers(id),
    trip_id bigint REFERENCES trips(id),
    lat double precision CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    lng double precision CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    speed double precision CHECK (speed IS NULL OR speed >= 0),
    confidence double precision CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    legacy_evidence_url varchar(500),
    status varchar(30) NOT NULL,
    handled_by bigint REFERENCES users(id),
    handled_at timestamptz(6),
    note varchar(500),
    client_event_id varchar(100),
    sync_batch_id bigint REFERENCES sync_batches(id),
    received_at timestamptz(6) NOT NULL DEFAULT now(),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_safety_driver_client_event ON safety_events (driver_id, client_event_id)
    WHERE client_event_id IS NOT NULL;
CREATE INDEX idx_safety_status_severity_created ON safety_events (status, severity, created_at DESC) WHERE NOT deleted;
CREATE INDEX idx_safety_trip_created ON safety_events (trip_id, created_at DESC) WHERE trip_id IS NOT NULL;

CREATE TABLE incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_code varchar(50) NOT NULL UNIQUE,
    type varchar(40) NOT NULL,
    severity varchar(30) NOT NULL,
    vehicle_id bigint REFERENCES vehicles(id),
    driver_id bigint REFERENCES drivers(id),
    trip_id bigint REFERENCES trips(id),
    lat double precision CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    lng double precision CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    description varchar(1000),
    status varchar(30) NOT NULL,
    assigned_to bigint REFERENCES users(id),
    accepted_at timestamptz(6),
    resolved_at timestamptz(6),
    client_event_id varchar(100),
    sync_batch_id bigint REFERENCES sync_batches(id),
    received_at timestamptz(6) NOT NULL DEFAULT now(),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_incident_driver_client_event ON incidents (driver_id, client_event_id)
    WHERE client_event_id IS NOT NULL;
CREATE INDEX idx_incidents_status_severity ON incidents (status, severity, created_at DESC) WHERE NOT deleted;

CREATE TABLE incident_timelines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id bigint NOT NULL REFERENCES incidents(id),
    action varchar(80) NOT NULL,
    actor_id bigint REFERENCES users(id),
    note varchar(500),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_incident_timelines_incident_created ON incident_timelines (incident_id, created_at);

CREATE TABLE flood_reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat double precision NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng double precision NOT NULL CHECK (lng BETWEEN -180 AND 180),
    address varchar(255),
    severity varchar(30) NOT NULL,
    source varchar(40) NOT NULL,
    reported_by_driver_id bigint REFERENCES drivers(id),
    image_asset_id bigint REFERENCES object_assets(id),
    legacy_image_url varchar(500),
    confidence double precision CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    status varchar(30) NOT NULL,
    verified_by bigint REFERENCES users(id),
    verified_at timestamptz(6),
    expired_at timestamptz(6),
    client_event_id varchar(100),
    sync_batch_id bigint REFERENCES sync_batches(id),
    received_at timestamptz(6) NOT NULL DEFAULT now(),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_flood_driver_client_event ON flood_reports (reported_by_driver_id, client_event_id)
    WHERE client_event_id IS NOT NULL;
CREATE INDEX idx_flood_status_expiry ON flood_reports (status, expired_at) WHERE NOT deleted;

CREATE TABLE safety_event_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    safety_event_id bigint REFERENCES safety_events(id),
    incident_id bigint REFERENCES incidents(id),
    uploaded_by bigint NOT NULL REFERENCES users(id),
    asset_id bigint NOT NULL REFERENCES object_assets(id),
    captured_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    deleted boolean NOT NULL DEFAULT false,
    CONSTRAINT ck_evidence_parent CHECK (safety_event_id IS NOT NULL OR incident_id IS NOT NULL)
);
CREATE INDEX idx_evidence_safety_event ON safety_event_evidence (safety_event_id) WHERE NOT deleted;
CREATE INDEX idx_evidence_incident ON safety_event_evidence (incident_id) WHERE NOT deleted;

CREATE TABLE maintenance_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maintenance_code varchar(50) NOT NULL UNIQUE,
    vehicle_id bigint NOT NULL REFERENCES vehicles(id),
    type varchar(30) NOT NULL,
    title varchar(150) NOT NULL,
    description varchar(1000),
    scheduled_date date,
    completed_date date,
    cost numeric(12,2) CHECK (cost IS NULL OR cost >= 0),
    status varchar(30) NOT NULL,
    priority varchar(30) NOT NULL,
    assigned_to bigint REFERENCES users(id),
    note varchar(1000),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_maintenance_vehicle_status ON maintenance_orders (vehicle_id, status) WHERE NOT deleted;

-- ---------------------------------------------------------------------------
-- Navigation
-- ---------------------------------------------------------------------------

CREATE TABLE navigation_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid varchar(100) NOT NULL UNIQUE,
    driver_id bigint NOT NULL REFERENCES drivers(id),
    vehicle_id bigint REFERENCES vehicles(id),
    trip_id bigint REFERENCES trips(id),
    origin_lat double precision NOT NULL CHECK (origin_lat BETWEEN -90 AND 90),
    origin_lng double precision NOT NULL CHECK (origin_lng BETWEEN -180 AND 180),
    destination_lat double precision NOT NULL CHECK (destination_lat BETWEEN -90 AND 90),
    destination_lng double precision NOT NULL CHECK (destination_lng BETWEEN -180 AND 180),
    destination_name varchar(255),
    status varchar(30) NOT NULL,
    started_at timestamptz(6),
    ended_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_navigation_sessions_driver_status ON navigation_sessions (driver_id, status) WHERE NOT deleted;

CREATE TABLE navigation_route_candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navigation_session_id bigint NOT NULL REFERENCES navigation_sessions(id) ON DELETE CASCADE,
    route_index integer NOT NULL,
    label varchar(120) NOT NULL,
    distance_meters integer NOT NULL CHECK (distance_meters >= 0),
    duration_seconds integer NOT NULL CHECK (duration_seconds >= 0),
    risk_score numeric(7,3) NOT NULL DEFAULT 0,
    total_score numeric(10,3) NOT NULL DEFAULT 0,
    flood_penalty numeric(10,3) NOT NULL DEFAULT 0,
    vehicle_restriction_penalty numeric(10,3) NOT NULL DEFAULT 0,
    driver_time_penalty numeric(10,3) NOT NULL DEFAULT 0,
    safe boolean NOT NULL DEFAULT true,
    blocked boolean NOT NULL DEFAULT false,
    flood_intersection_count integer NOT NULL DEFAULT 0 CHECK (flood_intersection_count >= 0),
    is_recommended boolean NOT NULL DEFAULT false,
    geometry_json jsonb NOT NULL,
    steps_json jsonb,
    warnings_json jsonb,
    provider varchar(40) NOT NULL DEFAULT 'LOCAL_DEMO',
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    UNIQUE (navigation_session_id, route_index)
);
CREATE INDEX idx_navigation_candidate_recommended ON navigation_route_candidates (navigation_session_id, is_recommended);

ALTER TABLE navigation_sessions ADD COLUMN selected_candidate_id bigint;
ALTER TABLE navigation_sessions ADD CONSTRAINT fk_navigation_selected_candidate
    FOREIGN KEY (selected_candidate_id) REFERENCES navigation_route_candidates(id);

CREATE TABLE navigation_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    navigation_session_id bigint NOT NULL REFERENCES navigation_sessions(id) ON DELETE CASCADE,
    event_type varchar(40) NOT NULL,
    lat double precision CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    lng double precision CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    distance_to_hazard_meters integer CHECK (distance_to_hazard_meters IS NULL OR distance_to_hazard_meters >= 0),
    distance_to_route_meters integer CHECK (distance_to_route_meters IS NULL OR distance_to_route_meters >= 0),
    gps_accuracy_meters numeric(8,2) CHECK (gps_accuracy_meters IS NULL OR gps_accuracy_meters >= 0),
    payload_json jsonb,
    occurred_at timestamptz(6) NOT NULL DEFAULT now(),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_navigation_events_session_time ON navigation_events (navigation_session_id, occurred_at);
CREATE INDEX idx_navigation_events_time_brin ON navigation_events USING brin (occurred_at);

-- ---------------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------------

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id bigint REFERENCES users(id),
    type varchar(40) NOT NULL,
    title varchar(150) NOT NULL,
    content varchar(500) NOT NULL,
    reference_type varchar(50),
    reference_id bigint,
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_recipient_created ON notifications (recipient_id, created_at DESC);

CREATE TABLE notification_reads (
    notification_id bigint NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read_at timestamptz(6) NOT NULL DEFAULT now(),
    PRIMARY KEY (notification_id, user_id)
);
CREATE INDEX idx_notification_reads_user ON notification_reads (user_id, read_at DESC);

CREATE TABLE push_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id bigint REFERENCES mobile_devices(id) ON DELETE CASCADE,
    provider varchar(30) NOT NULL,
    token varchar(512) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    last_used_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    UNIQUE (provider, token)
);
CREATE INDEX idx_push_tokens_user_enabled ON push_tokens (user_id, enabled);

CREATE TABLE pending_push_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id bigint REFERENCES notifications(id),
    user_id bigint NOT NULL REFERENCES users(id),
    push_token_id bigint REFERENCES push_tokens(id),
    title varchar(150) NOT NULL,
    body varchar(500) NOT NULL,
    data_json jsonb,
    status varchar(30) NOT NULL DEFAULT 'PENDING',
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at timestamptz(6) NOT NULL DEFAULT now(),
    sent_at timestamptz(6),
    last_error varchar(1000),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_pending_push_dispatch ON pending_push_notifications (status, next_attempt_at);

-- ---------------------------------------------------------------------------
-- Warehouse documents and OCR
-- ---------------------------------------------------------------------------

CREATE TABLE warehouse_issue_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id bigint UNIQUE REFERENCES trips(id),
    issue_number varchar(50) NOT NULL UNIQUE,
    issue_date date NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'DRAFT',
    document_version integer NOT NULL DEFAULT 1 CHECK (document_version > 0),
    company_name varchar(200),
    company_address varchar(255),
    issue_reason varchar(500),
    warehouse_name varchar(150) NOT NULL,
    warehouse_location varchar(150),
    project_name varchar(200) NOT NULL,
    work_item varchar(200),
    recipient_name varchar(150) NOT NULL,
    recipient_phone varchar(20),
    delivery_address varchar(255),
    prepared_by_user_id bigint REFERENCES users(id),
    prepared_by_name varchar(150),
    delivery_person_name varchar(150),
    driver_id bigint REFERENCES drivers(id),
    vehicle_id bigint REFERENCES vehicles(id),
    quantity_in_words varchar(500),
    notes varchar(1000),
    issued_at timestamptz(6),
    completed_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_warehouse_issue_status_date ON warehouse_issue_documents (status, issue_date DESC) WHERE NOT deleted;

CREATE TABLE warehouse_issue_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES warehouse_issue_documents(id) ON DELETE CASCADE,
    line_number integer NOT NULL CHECK (line_number > 0),
    item_code varchar(80),
    description varchar(255) NOT NULL,
    specification varchar(255),
    unit varchar(40) NOT NULL,
    requested_quantity numeric(14,3) CHECK (requested_quantity IS NULL OR requested_quantity >= 0),
    issued_quantity numeric(14,3) NOT NULL CHECK (issued_quantity >= 0),
    returned_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (returned_quantity >= 0),
    delivered_quantity numeric(14,3) CHECK (delivered_quantity IS NULL OR delivered_quantity >= 0),
    condition_note varchar(500),
    confirmation_note varchar(500),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false,
    UNIQUE (document_id, line_number)
);

CREATE TABLE warehouse_issue_confirmations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES warehouse_issue_documents(id) ON DELETE CASCADE,
    role_type varchar(30) NOT NULL,
    status varchar(30) NOT NULL,
    signer_name varchar(150) NOT NULL,
    signer_phone varchar(20),
    signed_at timestamptz(6),
    lat double precision CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    lng double precision CHECK (lng IS NULL OR lng BETWEEN -180 AND 180),
    evidence_asset_id bigint REFERENCES object_assets(id),
    legacy_evidence_url varchar(500),
    note varchar(500),
    created_by_user_id bigint REFERENCES users(id),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_warehouse_confirmation_document_role ON warehouse_issue_confirmations (document_id, role_type) WHERE NOT deleted;

CREATE TABLE warehouse_issue_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES warehouse_issue_documents(id),
    action varchar(50) NOT NULL,
    from_status varchar(30),
    to_status varchar(30),
    actor_user_id bigint REFERENCES users(id),
    actor_name varchar(150),
    note varchar(500),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_warehouse_audit_document_created ON warehouse_issue_audit_logs (document_id, created_at);

-- OCR lifecycle and business-record lifecycle are deliberately independent.
-- Saving manual fields must never change ocr_status or cancel a running job.
CREATE TABLE document_ocr_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id bigint NOT NULL REFERENCES users(id),
    driver_id bigint REFERENCES drivers(id),
    trip_id bigint REFERENCES trips(id),
    source_asset_id bigint NOT NULL REFERENCES object_assets(id),
    ocr_status varchar(20) NOT NULL DEFAULT 'QUEUED',
    record_status varchar(20) NOT NULL DEFAULT 'WAITING_OCR',
    version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
    original_filename varchar(255),
    content_type varchar(80) NOT NULL,
    project_address varchar(500),
    voucher_date date,
    voucher_number varchar(64),
    vehicle_plate varchar(32),
    expected_vehicle_plate varchar(32),
    driver_name varchar(255),
    trip_count integer CHECK (trip_count IS NULL OR trip_count >= 0),
    manual_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    ocr_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_text text,
    engine varchar(120),
    elapsed_ms bigint CHECK (elapsed_ms IS NULL OR elapsed_ms >= 0),
    error_code varchar(80),
    error_message varchar(1000),
    project_address_confidence numeric(5,4) CHECK (project_address_confidence IS NULL OR project_address_confidence BETWEEN 0 AND 1),
    voucher_date_confidence numeric(5,4) CHECK (voucher_date_confidence IS NULL OR voucher_date_confidence BETWEEN 0 AND 1),
    voucher_number_confidence numeric(5,4) CHECK (voucher_number_confidence IS NULL OR voucher_number_confidence BETWEEN 0 AND 1),
    vehicle_plate_confidence numeric(5,4) CHECK (vehicle_plate_confidence IS NULL OR vehicle_plate_confidence BETWEEN 0 AND 1),
    driver_name_confidence numeric(5,4) CHECK (driver_name_confidence IS NULL OR driver_name_confidence BETWEEN 0 AND 1),
    plate_review_status varchar(32) NOT NULL DEFAULT 'NOT_CHECKED',
    plate_review_reason varchar(255),
    reviewed_by_user_id bigint REFERENCES users(id),
    reviewed_at timestamptz(6),
    review_note varchar(500),
    started_at timestamptz(6),
    completed_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_document_ocr_owner_created ON document_ocr_jobs (owner_user_id, created_at DESC) WHERE NOT deleted;
CREATE INDEX idx_document_ocr_queue ON document_ocr_jobs (ocr_status, created_at) WHERE NOT deleted;
CREATE INDEX idx_document_ocr_record_status ON document_ocr_jobs (record_status, created_at DESC) WHERE NOT deleted;
CREATE INDEX idx_document_ocr_plate_review ON document_ocr_jobs (plate_review_status, created_at DESC) WHERE NOT deleted;

-- ---------------------------------------------------------------------------
-- Agent commands, settings and audit
-- ---------------------------------------------------------------------------

CREATE TABLE agent_commands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    driver_id bigint REFERENCES drivers(id),
    trip_id bigint REFERENCES trips(id),
    command_type varchar(30) NOT NULL,
    transcript varchar(1000) NOT NULL,
    normalized_command varchar(255),
    interpreted_intent varchar(40),
    confidence double precision CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    requires_confirmation boolean NOT NULL DEFAULT false,
    classification_source varchar(30),
    status varchar(30) NOT NULL DEFAULT 'RECEIVED',
    response_text text,
    executed_reference_type varchar(40),
    executed_reference_id bigint,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_agent_user_created ON agent_commands (user_id, created_at DESC) WHERE NOT deleted;

CREATE TABLE system_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key varchar(100) NOT NULL,
    setting_group varchar(40) NOT NULL,
    setting_value text NOT NULL,
    value_type varchar(30) NOT NULL,
    description varchar(255),
    updated_by bigint REFERENCES users(id),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_system_settings_key_active ON system_settings (setting_key) WHERE NOT deleted;
CREATE INDEX idx_system_settings_group ON system_settings (setting_group) WHERE NOT deleted;

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id bigint REFERENCES users(id),
    action varchar(120) NOT NULL,
    target_type varchar(80),
    target_id bigint,
    ip_address inet,
    user_agent varchar(500),
    context_json jsonb,
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_logs_actor_created ON audit_logs (actor_id, created_at DESC);
CREATE INDEX idx_audit_logs_target ON audit_logs (target_type, target_id);
CREATE INDEX idx_audit_logs_created_brin ON audit_logs USING brin (created_at);
