-- RAG, semantic search and server-side agent execution trace.
-- Requires pgvector to be installed in the PostgreSQL image.

SET search_path TO safefleet, public;
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE rag_collections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    description text,
    embedding_provider varchar(50) NOT NULL,
    embedding_model varchar(120) NOT NULL,
    embedding_dimensions integer NOT NULL DEFAULT 1536 CHECK (embedding_dimensions = 1536),
    distance_metric varchar(20) NOT NULL DEFAULT 'COSINE' CHECK (distance_metric IN ('COSINE', 'L2', 'INNER_PRODUCT')),
    status varchar(30) NOT NULL DEFAULT 'ACTIVE',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_by_user_id bigint REFERENCES users(id),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX uk_rag_collections_name_active ON rag_collections (lower(name)) WHERE NOT deleted;

CREATE TABLE rag_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id bigint NOT NULL REFERENCES rag_collections(id),
    title varchar(500) NOT NULL,
    source_type varchar(40) NOT NULL,
    source_uri varchar(1000),
    current_asset_id bigint REFERENCES object_assets(id),
    owner_user_id bigint REFERENCES users(id),
    status varchar(30) NOT NULL DEFAULT 'PENDING',
    language_code varchar(20) NOT NULL DEFAULT 'vi',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_rag_documents_collection_status ON rag_documents (collection_id, status) WHERE NOT deleted;
CREATE INDEX idx_rag_documents_title_trgm ON rag_documents USING gin (title public.gin_trgm_ops) WHERE NOT deleted;

CREATE TABLE rag_document_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES rag_documents(id) ON DELETE CASCADE,
    version_number integer NOT NULL CHECK (version_number > 0),
    source_asset_id bigint REFERENCES object_assets(id),
    source_sha256 char(64) NOT NULL,
    extracted_text text,
    parser_name varchar(120),
    parser_version varchar(80),
    extraction_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    status varchar(30) NOT NULL DEFAULT 'PENDING',
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    UNIQUE (document_id, version_number),
    CONSTRAINT ck_rag_source_sha256 CHECK (source_sha256 ~ '^[0-9a-fA-F]{64}$')
);
CREATE INDEX idx_rag_document_versions_document ON rag_document_versions (document_id, version_number DESC);

CREATE TABLE rag_chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id bigint NOT NULL REFERENCES rag_document_versions(id) ON DELETE CASCADE,
    chunk_index integer NOT NULL CHECK (chunk_index >= 0),
    content text NOT NULL,
    token_count integer CHECK (token_count IS NULL OR token_count >= 0),
    page_from integer CHECK (page_from IS NULL OR page_from > 0),
    page_to integer CHECK (page_to IS NULL OR page_to > 0),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    embedding public.vector(1536),
    search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    UNIQUE (document_version_id, chunk_index),
    CONSTRAINT ck_rag_chunk_page_range CHECK (page_to IS NULL OR page_from IS NULL OR page_to >= page_from)
);
CREATE INDEX idx_rag_chunks_document_version ON rag_chunks (document_version_id, chunk_index);
CREATE INDEX idx_rag_chunks_search ON rag_chunks USING gin (search_vector);
CREATE INDEX idx_rag_chunks_metadata ON rag_chunks USING gin (metadata jsonb_path_ops);
CREATE INDEX idx_rag_chunks_embedding_hnsw ON rag_chunks USING hnsw (embedding public.vector_cosine_ops)
    WHERE embedding IS NOT NULL;

CREATE TABLE rag_ingestion_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id bigint NOT NULL REFERENCES rag_document_versions(id) ON DELETE CASCADE,
    status varchar(30) NOT NULL DEFAULT 'QUEUED',
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempts integer NOT NULL DEFAULT 3 CHECK (max_attempts > 0),
    next_attempt_at timestamptz(6) NOT NULL DEFAULT now(),
    locked_by varchar(120),
    locked_at timestamptz(6),
    started_at timestamptz(6),
    completed_at timestamptz(6),
    error_code varchar(80),
    error_message text,
    metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    updated_at timestamptz(6)
);
CREATE INDEX idx_rag_ingestion_dispatch ON rag_ingestion_jobs (status, next_attempt_at);

-- Access is evaluated before retrieval. Exactly one grantee type must be set.
CREATE TABLE rag_access_grants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id bigint REFERENCES rag_collections(id) ON DELETE CASCADE,
    document_id bigint REFERENCES rag_documents(id) ON DELETE CASCADE,
    user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    role_id bigint REFERENCES roles(id) ON DELETE CASCADE,
    permission varchar(20) NOT NULL DEFAULT 'READ' CHECK (permission IN ('READ', 'WRITE', 'ADMIN')),
    granted_by_user_id bigint REFERENCES users(id),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT ck_rag_grant_resource CHECK (
        (collection_id IS NOT NULL AND document_id IS NULL)
        OR (collection_id IS NULL AND document_id IS NOT NULL)
    ),
    CONSTRAINT ck_rag_grant_principal CHECK (
        (user_id IS NOT NULL AND role_id IS NULL)
        OR (user_id IS NULL AND role_id IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uk_rag_grant_collection_user ON rag_access_grants (collection_id, user_id, permission)
    WHERE collection_id IS NOT NULL AND user_id IS NOT NULL;
CREATE UNIQUE INDEX uk_rag_grant_collection_role ON rag_access_grants (collection_id, role_id, permission)
    WHERE collection_id IS NOT NULL AND role_id IS NOT NULL;
CREATE UNIQUE INDEX uk_rag_grant_document_user ON rag_access_grants (document_id, user_id, permission)
    WHERE document_id IS NOT NULL AND user_id IS NOT NULL;
CREATE UNIQUE INDEX uk_rag_grant_document_role ON rag_access_grants (document_id, role_id, permission)
    WHERE document_id IS NOT NULL AND role_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Agent conversations and auditable tool execution
-- ---------------------------------------------------------------------------

CREATE TABLE ai_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    user_id bigint NOT NULL REFERENCES users(id),
    driver_id bigint REFERENCES drivers(id),
    title varchar(255),
    channel varchar(30) NOT NULL DEFAULT 'MOBILE',
    status varchar(30) NOT NULL DEFAULT 'ACTIVE',
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at timestamptz(6) NOT NULL DEFAULT now(),
    last_message_at timestamptz(6) NOT NULL DEFAULT now(),
    closed_at timestamptz(6),
    deleted boolean NOT NULL DEFAULT false
);
CREATE INDEX idx_ai_conversations_user_recent ON ai_conversations (user_id, last_message_at DESC) WHERE NOT deleted;

CREATE TABLE ai_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
    role varchar(20) NOT NULL CHECK (role IN ('SYSTEM', 'USER', 'ASSISTANT', 'TOOL')),
    content text,
    content_json jsonb,
    provider_message_id varchar(255),
    input_tokens integer CHECK (input_tokens IS NULL OR input_tokens >= 0),
    output_tokens integer CHECK (output_tokens IS NULL OR output_tokens >= 0),
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    CONSTRAINT ck_ai_message_content CHECK (content IS NOT NULL OR content_json IS NOT NULL)
);
CREATE INDEX idx_ai_messages_conversation_created ON ai_messages (conversation_id, created_at);

CREATE TABLE ai_agent_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    conversation_id bigint NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
    request_message_id bigint REFERENCES ai_messages(id),
    response_message_id bigint REFERENCES ai_messages(id),
    provider varchar(50) NOT NULL,
    model varchar(120) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'PLANNING',
    plan_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    current_step integer NOT NULL DEFAULT 0 CHECK (current_step >= 0),
    replan_count integer NOT NULL DEFAULT 0 CHECK (replan_count >= 0),
    permission_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    error_code varchar(80),
    error_message text,
    started_at timestamptz(6) NOT NULL DEFAULT now(),
    completed_at timestamptz(6),
    created_at timestamptz(6) NOT NULL DEFAULT now()
);
CREATE INDEX idx_ai_agent_runs_conversation ON ai_agent_runs (conversation_id, created_at DESC);
CREATE INDEX idx_ai_agent_runs_status ON ai_agent_runs (status, created_at);

CREATE TABLE ai_tool_calls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id bigint NOT NULL REFERENCES ai_agent_runs(id) ON DELETE CASCADE,
    step_index integer NOT NULL CHECK (step_index >= 0),
    tool_name varchar(150) NOT NULL,
    mcp_server varchar(120),
    required_permission varchar(100),
    authorization_result varchar(30) NOT NULL,
    input_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    output_json jsonb,
    status varchar(30) NOT NULL DEFAULT 'PENDING',
    idempotency_key varchar(160),
    started_at timestamptz(6),
    completed_at timestamptz(6),
    error_code varchar(80),
    error_message text,
    created_at timestamptz(6) NOT NULL DEFAULT now(),
    UNIQUE (run_id, step_index)
);
CREATE INDEX idx_ai_tool_calls_tool_created ON ai_tool_calls (tool_name, created_at DESC);
CREATE UNIQUE INDEX uk_ai_tool_call_idempotency ON ai_tool_calls (idempotency_key)
    WHERE idempotency_key IS NOT NULL;
